services:
  node-red:
    image: nodered/node-red:latest
    ports:
      - 1880:1880
    volumes:
      - node-red-practica:/data

    environment:
      - TZ=Europe/Madrid

volumes:
  node-red-practica: